### ISSUE TITLE
Target humidity with input_number

### ISSUE THREAD

**Issue by RomchikL** [artem-sedykh/mini-humidifier#103]
deerma.humidifier.mjjsq has an issue: 
In "Humidity=Auto" mode the target_humidity attribute works fine, but in all other modes (Low, Medium, High) the target_humidity attribute equals 0 (automatically).
So, I changed it with input_number and some automations ([see](https://github.com/syssi/xiaomi_airpurifier#input-number-example) for details)

```
    input_number:
        lr_humidifier_target_humidity:
          name: Favorite Level
          initial: 50
          min: 30
          max: 60
          step: 1

        - type: custom:mini-humidifier
          entity: fan.lr_humidifier
          name: Hum
          model: 'xiaomi_miio_airpurifier:deerma.humidifier.mjjsq'
          target_humidity:
            state:
              entity: input_number.lr_humidifier_target_humidity
```
But now I cannot change the value of the input_number via the mini-humidifier card. 
I try to change (e.g. from 50 to 40), but it becomes back 50 and nothing changes.
