### ISSUE TITLE
Add support for type switch and external humidity sensor

### ISSUE THREAD

**Issue by LuisDiazUgena** [artem-sedykh/mini-humidifier#122]
It would be useful to have that support to be able to use it with dumb humidifiers controller by a smart switch.

**Comment by regevbr** [comment]
This will be a big refactor. A PR will be great, and I would gladly review it and merge

**Comment by artem-sedykh** [comment]
This works now, and it needs no refactor of the card - the answer turned out to
be a preset rather than a feature.

Home Assistant already turns "a dumb humidifier on a switch plus an external
humidity sensor" into a single entity, with
[generic_hygrostat](https://www.home-assistant.io/integrations/generic_hygrostat/):

```yaml
generic_hygrostat:
  - name: Bedroom humidifier
    humidifier: switch.bedroom_humidifier_plug
    target_sensor: sensor.bedroom_humidity
    min_humidity: 30
    max_humidity: 70
```

What comes out is a `humidifier.*` entity, and the card now has a preset built
on exactly that domain rather than on a particular Xiaomi:

```yaml
type: custom:mini-humidifier
entity: humidifier.bedroom_humidifier
model: humidifier
```

Power, the target humidity slider with the range the hygrostat reports, and the
current reading - nothing else to write.

If you would rather drive the switch and the sensor directly, without a
hygrostat, that also works: `model: none` brings no controls at all, and the
power button, the reading and any buttons are described in YAML. `docs/models.md`
and `docs/buttons.md` have worked examples, including a button that reads and
drives an entity other than the card's own.

On master, in HACS with the next release. Closing - please reopen if your setup
does not fit either shape.
