### ISSUE TITLE
Levoit Classic 300S Humidifier

### ISSUE THREAD

**Issue by Scope666** [artem-sedykh/mini-humidifier#124]
Hi,

I mostly have this card working, I just can't figure out how to control the night light.

It's a separate entity_id in the integration:  **light.classic300s_night_light**

```
type: custom:mini-humidifier
entity: humidifier.classic300s
indicators:
  humidity:
    icon: mdi:water
    unit: '%'
    source:
      entity: sensor.classic300s_current_humidity
buttons:
  led:
    icon: mdi:lightbulb-on-outline
    order: 2
    type: dropdown
    entity_id: light.classic300s_night_light
    state:
      attribute: brightness
    source:
      '0': '80'
      '1': '50'
      '2': 'Off'
    active: state => (state !== 2 && state !== '2')
    change_action: |
      (selected, state, entity) => {
        const options = { entity_id: entity.entity_id, brightness: selected };
        return this.call_service('light', 'turn_on', options);
      }
```

I'm not really a coder, so I know what I have for the LED / Light is wrong.  

Any advice for modifying to call light.turn_on and adjust brightness ?

<img width="952" alt="image" src="https://github.com/artem-sedykh/mini-humidifier/assets/31927547/ec0bb5aa-36da-4591-a0a5-58ec82a22f03">

**Comment by regevbr** [comment]
just practice the service call in the dev dashboard and see what works for you

**Comment by artem-sedykh** [comment]
Late, but here is the answer, and the reason it did not work.

**`entity_id:` at the top of a button is not an option the card reads.** Keys it
does not recognise are left alone on purpose - they become the template scope,
readable as `this.entity_id` - so the button looked configured and acted on the
humidifier instead. The option that points a button at another entity is
`state: entity`, and that entity is also the one the button's templates are
handed.

For the night light:

```yaml
type: custom:mini-humidifier
entity: humidifier.classic300s
model: humidifier
indicators:
  humidity:
    icon: mdi:water
    unit: '%'
    source:
      entity: sensor.classic300s_current_humidity
buttons:
  night_light:
    icon: mdi:lightbulb-night
    type: dropdown
    order: 2
    state:
      entity: light.classic300s_night_light
      attribute: brightness
    source:
      '0': 'Off'
      '128': 'Dim'
      '255': 'Bright'
    active: (state) => Number(state) > 0
    change_action: |
      (selected, state, entity) => {
        const options = { entity_id: entity.entity_id, brightness: Number(selected) };
        return this.call_service('light', 'turn_on', options);
      }
```

Check the actual `brightness` values your integration reports in Developer tools
-> States and use those as the keys - VeSync reports a plain 0-255 for some
models and a small step count for others.

Two other things that are new since you asked:

- `model: humidifier` is a preset built on the `humidifier` domain rather than on
  a Xiaomi, which is what your Classic 300S wants as a base;
- `docs/buttons.md` now has a section on buttons for another entity, with the
  short form (a plain switch needs `state: entity` and nothing else, because a
  button with no `toggle_action` calls `switch.toggle` on its own entity).

Both are on master and reach HACS with the next release. Closing - reopen if the
dropdown does not drive your light.
