### ISSUE TITLE
default settings for different models of humidifiers

### ISSUE THREAD

**Issue by artem-sedykh** [artem-sedykh/mini-humidifier#24]
It would be cool to put the configuration of the humidifiers in a separate file and in the settings just indicate the type.
Now the default settings are made for the model `zhimi.humidifier.cb1`

As an example:
```yaml
- type: custom:mini-humidifier
  entity: fan.xiaomi_miio_device
  model: 'zhimi.humidifier.cb1'
```
