### ISSUE TITLE
Purifier

### ISSUE THREAD

**Issue by abcjoint** [artem-sedykh/mini-humidifier#27]
Is it possible to add Xiaomi purifier support to your plugin?

**Comment by artem-sedykh** [comment]
of course you can add

**Comment by abcjoint** [comment]
It seems, I need help..
```
entity: fan.purifier
target_humidity:
  change_action: |
    (selected, _, entity) => {
      const options = { entity_id: entity.entity_id, fan_set_favorite_level: selected };
      return this.call_service('xiaomi_miio', 'fan_set_favorite_level', options);
    }
  icon: 'mdi:fan'
  max: 14
  min: 0
  state:
    attribute: sensor.xiaomi_airpurifier_speed
  step: 1
  unit: ''
type: 'custom:mini-humidifier'

```
tried this setting, got an error
<img width="663" alt="screenshot 2020-06-09 в 23 04 01" src="https://user-images.githubusercontent.com/66694785/84194403-a868fd00-aaa5-11ea-9c80-af706102842e.png">

**Comment by artem-sedykh** [comment]
What integration do you use?  
This? https://www.home-assistant.io/integrations/fan.xiaomi_miio/
try like this
`const options = { entity_id: entity.entity_id, level: selected };`

**Comment by abcjoint** [comment]
Yes, it works!
Thanks!
is it possible to show rpm?
  state:
    attribute: sensor.xiaomi_airpurifier_speed
 - doesn't work

**Comment by artem-sedykh** [comment]
You can try calling the service at http://ip or name/developer-tools/service sometimes there are even examples

![image](https://user-images.githubusercontent.com/861063/84195336-0d712280-aaa7-11ea-8e46-8a3339dae285.png)

**Comment by abcjoint** [comment]
<img width="543" alt="screenshot 2020-06-09 в 23 18 27" src="https://user-images.githubusercontent.com/66694785/84195675-a56f0c00-aaa7-11ea-92f6-aab7145dd737.png">
how to change this parameter to `motor_speed`?

**Comment by artem-sedykh** [comment]
```yaml
- type: custom:mini-humidifier
  entity: fan.xiaomi_miio_device
  indicators:
    depth:
      hide: on
    motor_speed:
      icon: your icon
      source:
        attribute: motor_speed
      ...
```
