### ISSUE TITLE
Настройки одной карты распространяются на все

### ISSUE THREAD

**Issue by profx5015** [artem-sedykh/mini-humidifier#28]
Добрый день!
Столкнулся со следующей проблемой: при задании настроек для одной карты, на другой они дублируются.
<img width="425" alt="Снимок экрана 2020-06-10 в 10 23 32" src="https://user-images.githubusercontent.com/4104873/84239098-af732800-ab04-11ea-99b9-9d531f7e5b2b.png">

Код очистителя:
```
type: 'custom:mini-humidifier'
entity: fan.purifier
name: Очиститель
indicators:
  depth:
    hide: 'on'
  motor_speed:
    icon: 'mdi:fan'
    order: 0
    unit: rpm
    source:
      attribute: motor_speed
  filter_life_remaining:
    icon: 'mdi:heart'
    order: 0
    unit: '%'
    source:
      attribute: filter_life_remaining
  average_aqi:
    icon: 'mdi:weather-fog'
    order: 0
    unit: μg/m³
    source:
      attribute: average_aqi
target_humidity:
  change_action: |
    (selected, _, entity) => {
      const options = { entity_id: entity.entity_id, level: selected };
      return this.call_service('xiaomi_miio', 'fan_set_favorite_level', options);
    }
  icon: 'mdi:fan'
  max: 14
  min: 0
  state:
    attribute: favorite_level
  step: 1
  unit: ''

```

Код увлажнителя:
```

entity: fan.humidifier
name: Увлажнитель
target_humidity:
  change_action: |
    (selected, _, entity) => {
      const options = { entity_id: entity.entity_id, humidity: selected };
      return this.call_service('xiaomi_miio', 'fan_set_target_humidity', options);
    }
  icon: 'mdi:water'
  max: 80
  min: 30
  state:
    attribute: target_humidity
  step: 10
  unit: '%'
type: 'custom:mini-humidifier'


```
