### ISSUE TITLE
No option for Fahrenheit?

### ISSUE THREAD

**Issue by JoeStratton** [artem-sedykh/mini-humidifier#45]
```
temperature:
  unit: '°F'
```
Does not set the temperature value, it wont change from Celsius. Is this possible? I tried without the special symbol as well.

**Comment by artem-sedykh** [comment]
You seem to have forgotten the section `indicators`  
```yaml
  - entity: fan.zhimi_humidifier_cb1
    type: custom:mini-humidifier
    icon: mdi:air-filter
    model: 'zhimi.humidifier.cb1'
    indicators:
      temperature:
        unit: '°F'
```

![image](https://user-images.githubusercontent.com/861063/102718463-43fee400-42f9-11eb-9262-61c261022445.png)
