### ISSUE TITLE
cannot specify target_humidity: state: entity

### ISSUE THREAD

**Issue by jacekpaszkowski** [artem-sedykh/mini-humidifier#46]
Hi, i think there is a bug. Setting entity for state of target_humidity doesn't work.

```yaml
        target_humidity:
          state:
            entity: input_number.target_fan_salon_humiditifier_2
```
The result is:
![image](https://user-images.githubusercontent.com/4264991/99963526-36098200-2d92-11eb-9b29-43aa909576d3.png)
