### ISSUE TITLE
Group switch on CARD ?

### ISSUE THREAD

**Issue by AntoxaSa** [artem-sedykh/mini-humidifier#53]
Подскажите,как сделать отдельную кнопку в карточке на отдельный свитч?
Tell me how to make a separate button in the card for a separate group switch?
auto:
                icon: 'mdi:brightness-auto'
                order: 5
                state:
                    entity: group.manual_brizer 
                    mapper: "(state) => (state ? 'on' : 'off')"
                toggle_action: >

**Comment by AgenTer85** [comment]
Я имею такую же проблему. Хочу сделать дополнительную кнопку в мини-карточке, но не один из способов не работает. Переключение не происходит.
I have the same problem. I want to make an additional button in the mini-card, but not one of the ways does not work. The switch does not occur.

**Comment by bisquit2003** [comment]
так же хотел бы добавить отдельную кнопку в карточку, которая отвечает за подогрев воды в увлажнителе, у меня модель сяоми про, там этот функционал интеграцией передается отдельным свитчем
пока накидал такую карточку для отображения уровня воды из отдельного сенсора:

type: custom:mini-humidifier
entity: humidifier.leshow_jsq1_ee06_humidifier #увлажнитель
indicators:
  water:
    icon: mdi:cup-water
    unit: '%'
    round: 1
    source:
      entity: sensor.leshow_jsq1_ee06_water_level #сенсор уровня воды

в идеале бы еще яркость дисплея, интеграция передает отдельной сущностью number.leshow_jsq1_ee06_screen_brightness со значениями 0 и 1, наверное можно через сервис, не пробовал еще

**Comment by artem-sedykh** [comment]
Sorry this sat unanswered - three people asked the same thing in this thread and
none of you were ever shown a configuration that works. Here it is.

The option that points a button at another entity is `state: entity`. That
entity is also the one the button's templates receive as their second argument,
which is the part every attempt in this thread got wrong.

**For a plain switch, nothing else is needed:**

```yaml
type: custom:mini-humidifier
entity: humidifier.bedroom
buttons:
  heater:
    icon: mdi:radiator
    order: 5
    state:
      entity: switch.bedroom_humidifier_heater
```

A button with no `toggle_action` calls `switch.toggle` on its own entity, and
the icon lights up on any state that is not `off` - so no mapper and no action
template.

**For a `group.*` entity, say the service**, because groups answer
`homeassistant.turn_on` / `turn_off` rather than `switch.*`:

```yaml
buttons:
  brizer:
    icon: mdi:brightness-auto
    order: 5
    state:
      entity: group.manual_brizer
    toggle_action: |
      (state, entity) => {
        const service = state === 'on' ? 'turn_off' : 'turn_on';
        return this.call_service('homeassistant', service, { entity_id: entity.entity_id });
      }
```

`docs/buttons.md` now has a section on this, with a third example for a dropdown
over another entity's attribute. Two of those examples are covered by the
browser tests, so they are run rather than written.

One more thing worth knowing if a button of yours ever simply does not appear:
from the next release the card names in the browser console any entity it was
configured with and could not find. Silence there used to be the whole of the
diagnosis.

Closing - please reopen if your switch still will not toggle.
