### ISSUE TITLE
zhimi.humidifier.ca4 speed error

### ISSUE THREAD

**Issue by JD99** [artem-sedykh/mini-humidifier#54]
hi.  
model: zhimi.humidifier.ca4 

config lovelace:
```
      - type: vertical-stack
        cards: 
        - type: custom:mini-humidifier
          toggle:
            default: on
            hide: off
          entity: fan.xiaomi_smartmi_air_humidifier_2
          model: 'zhimi.humidifier.ca4' 
```
config fan
```
  - platform: xiaomi_miio
    name: Xiaomi Smartmi Air Humidifier 2
    host: 192.168.2.146
    token: !secret xiaomi_fan_token
    model: zhimi.humidifier.ca4
```

Error when changing speed
```
    auto: dont work
    silent: dont work
    medium: work
    high: work
```
Error text
`Failed to call service fan/set_speed. 'auto'`
