### ISSUE TITLE
How to apply the "color" style to values?

### ISSUE THREAD

**Issue by samoswall** [artem-sedykh/mini-humidifier#71]
В примерах описано как можно менять цвет **значка** в зависимости от значения датчика:
The examples describe how you can change the color of the **icon** depending on the sensor value:
```
- type: custom:mini-humidifier
  entity: fan.xiaomi_miio_device
  indicators:
    depth:
      icon:
        template: >
          (value) => {
            if (value === 0)
              return "mdi:tray";
            if (value <= 20)
              return "mdi:tray-minus";
            return "mdi:tray-full";
          }
        style: >
          (value) => {
            if (value === 0)
              return { color: "red" };
            if (value <= 20)
              return { color: "#FD451D" };
            return {};
          }
```
Это можно сделать для **значков** температуры и влажности (например: t<=20 синий цвет, 20<t<30 зеленый цвет, t>=30 красный цвет)
This can be done for temperature and humidity **icons** (for example: t<=20 blue, 20<t<30 green, t>=30 red)

Как прописать правило для изменения цвета **текста** значения?  (цифры)
How do I write a rule for changing the color of the **text** value? (numbers)

**Comment by Krocko** [comment]
This option don’t work anymore for my too. 
The last working version was 2.4.1.

**Comment by artem-sedykh** [comment]
This is implemented. An indicator's style now reaches the reading, not only the
icon beside it:

```yaml
type: custom:mini-humidifier
entity: fan.xiaomi_miio_device
indicators:
  depth:
    value:
      style: |
        (value) => {
          if (value === 0) return { color: 'red' };
          if (value <= 20) return { color: 'orange' };
          return {};
        }
```

`value: style` colours the number and the unit after it; `icon: style` keeps
doing what it always did. They are two options rather than one, because an icon
style is often geometry as well as colour - the bundled AQI indicators set
`--mdc-icon-size` and a margin in theirs - and that has no business on the
reading.

`docs/indicators.md` has an example that reuses the same table of levels for
both. On master; in HACS with the next release.

One correction to the second comment in this thread: this did not work up to
2.4.1. The indicator render is the same in v2.0.1, v2.4.1 and v3.0.1, with the
style on `ha-icon` alone - so nothing was removed, the option simply never
existed until now. If what stopped working for you was the **icon** colour
rather than the value's, that is a different problem and worth its own issue
with a configuration.

Closing as done.
