### ISSUE TITLE
Icons not shown on entities card

### ISSUE THREAD

**Issue by Anonym-tsk** [artem-sedykh/mini-humidifier#89]
My configuration:

```yaml
type: entities
entities:
  - type: custom:mini-humidifier
    entity: fan.mi_humidifier
    model: xiaomi_miio_airpurifier:deerma.humidifier.mjjsq
    name: Увлажнитель в спальне
    group: true
  - type: custom:mini-humidifier
    entity: fan.mi_humidifier_kids
    model: xiaomi_miio_airpurifier:deerma.humidifier.mjjsq
    name: Увлажнитель в детской
    group: true
  - type: custom:mini-humidifier
    entity: fan.mi_humidifier_old
    model: xiaomi_miio_airpurifier:deerma.humidifier.mjjsq
    name: Увлажнитель старый
    icon: mdi:air-purifier
    group: true
```

There are no icons:

![image](https://user-images.githubusercontent.com/1973755/170068185-d3462dfd-a79a-41a1-a898-9cb9eeba8182.png)

**But (!!!)** if i add card with one humidifier:

```yaml
type: custom:mini-humidifier
entity: fan.mi_humidifier
model: xiaomi_miio_airpurifier:deerma.humidifier.mjjsq
```

It fixes all humidifiers on all cards:

![image](https://user-images.githubusercontent.com/1973755/170069058-cb56b990-b19e-4949-83a3-f2c7979ea58d.png)
